### ISSUE TITLE
Getting error successCallback is not a function

### ISSUE THREAD

**Issue by bkrajendra** [scottdermott/cordova-plugin-discovery#6]
Error in Success callbackId: serviceDiscovery1097938893 : TypeError: successCallback is not a function

**Comment by scottdermott** [comment]
Hi,

What platform are you developing on (iOS/Android)?

Can you send me an example of how you are calling the serviceDiscovery API?

Thanks

**Comment by bkrajendra** [comment]
Android.
Recently I was trying to migrate to new ionic 2+ version.
I copied entire code and also updated to latest SSDP plugin.

Now when i run , im getting this error, 
everything looks in place. butn dont know why it throwing this error .

```javascript
	$scope.RunDiscovery = function()
	{
		console.log("im in scan discovery...");
		$scope.show();
		try {
			serviceDiscovery.getNetworkServices(serviceType, true, $scope.fsuccess, $scope.ffailure);
		}
		catch(err) {
			console.log(err+' - Error in SSDP');
			$scope.hide();
			$scope.$broadcast('scroll.refreshComplete');
		}
		
	}
	$scope.fsuccess = function(devices)
	{
		//store.set('board',devices);
	}

	$scope.ffailure = function()
	{
		console.log("Failed..");
	}

```

**Comment by scottdermott** [comment]
The API has changed slightly since your implementation. Some refactoring took place and as a result the GET request for the config.xml is now handled in the native code instead of the JS. So the 2nd param is no longer necessary.

`serviceDiscovery.getNetworkServices(serviceType, true, $scope.fsuccess, $scope.ffailure);`

Change to:
`serviceDiscovery.getNetworkServices(serviceType, $scope.fsuccess, $scope.ffailure);`
